export const SUDO_PROTOCOL_VERSION = "0.1.0";

export const UNKNOWN_MAX_PENDING_PER_RECIPIENT = 3;
export const KNOWN_MAX_PENDING_PER_PAIR = 100;
export const UNKNOWN_TTL_HOURS = 72;
export const KNOWN_TTL_DAYS = 30;
export const DEFAULT_MAX_TEXT_MESSAGE_BYTES = 16 * 1024;
export const DEFAULT_MAX_TEXT_FEED_POST_BYTES = 16 * 1024;
export const DEFAULT_RELAY_GLOBAL_PENDING_CAP = 100000;
export const DEFAULT_RELAY_RECIPIENT_PENDING_CAP = 1000;
export const DEFAULT_RELAY_SENDER_PENDING_CAP = 500;

export const DEFAULT_MESSAGE_TTL_UNKNOWN_HOURS = UNKNOWN_TTL_HOURS;
export const DEFAULT_MESSAGE_TTL_KNOWN_DAYS = KNOWN_TTL_DAYS;
export const MAX_UNKNOWN_PENDING_MESSAGES = UNKNOWN_MAX_PENDING_PER_RECIPIENT;
